print("===========Assignment Comma Operator==========");
var a = 1;
print(a == 1? "success" : "fail");
a *=10;
print(a == 10? "success" : "fail");
a/=10;
print(a == 1? "success" : "fail");
a%=10;
print(a == 1? "success" : "fail");
a-=10;
print(a == -9? "success" : "fail");
